---
  - name: Update apt cache
    apt: update_cache=yes cache_valid_time=5400

  - name: Add pip
    apt: name=python-pip 

  - name: Add rabbitmq-server
    apt: name=rabbitmq-server

  - name: Add pika
    pip: name=pika

  - name: Add flask
    pip: name=flask
